export const tinymceConfig = {
    // selector: "textarea",
    height: "75vh",
    width: "100vw",
    statusbar: false,
    resize: false,
    min_height: 450,
    max_height: 1000,
    branding:false,
    promotion:false,
    autoresize_bottom_margin: 0,
    autosave_ask_before_unload: true,
    skin: 'tinymce-5-dark',
    content_css: 'dark',
    theme: 'silver',
    highlight_on_focus: true,
    plugins: [
        "tinycomments",
        "mentions",
        "anchor",
        "autosave",
        "autolink",
        "charmap",
        "codesample",
        "emoticons",
        "image",
        "link",
        "lists",
        "media",
        "searchreplace",
        "table",
        "visualblocks",
        "wordcount",
        "checklist",
        "mediaembed",
        "casechange",
        "export",
        "formatpainter",
        "pageembed",
        "permanentpen",
        "footnotes",
        "advtemplate",
        "advtable",
        "advcode",
        "editimage",
        "tableofcontents",
        "mergetags",
        "powerpaste",
        "tinymcespellchecker",
        "autocorrect",
        "a11ychecker",
        "typography",
        "inlinecss"
      ],
    toolbar:
      "undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat | restoredraft",
    tinycomments_mode: "embedded",
    tinycomments_author: "Author name",
    mergetags_list: [
      { value: "First.Name", title: "First Name" },
      { value: "Email", title: "Email" },
    ]
  }